export const UPDATE_CURRENT_DATA = 'UPDATE_CURRENT_DATA'

export  const INIT_GET_STORED_DATA = 'INIT_GET_STORED_DATA'

export const UPDATE_STORED_DATA = 'UPDATE_STORED_DATA'

export const EDIT_STORED_DATA = 'EDIT_STORED_DATA'
